# Generated by Django 4.1.2 on 2022-10-05 08:42

from django.db import migrations, models
import tinymce_4.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', tinymce_4.fields.TinyMCEModelField(verbose_name='Foo content')),
            ],
        ),
    ]
