# Generated by Django 4.1.2 on 2022-10-05 09:09

from django.db import migrations, models
import tinymce_4.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo1Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', tinymce_4.fields.TinyMCEModelField(verbose_name='Foo content')),
            ],
        ),
    ]
