# Generated by Django 4.1.2 on 2022-10-05 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_demo1model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Demo1Model',
        ),
    ]
